# =============================================================================
# Title: Simulate panel data with bad controls
# Description: Generates staggered DiD panel data with known group-time,
#   event-study, and overall ATT, for testing bad-control estimators. dgp1
#   and dgp3 match the Monte Carlo designs in Caetano, Callaway, Payne, and
#   Sant'Anna (2026); dgp2/dgp4/dgp5 are this package's own designs (dgp2 was
#   originally a literal replica of the paper's "Nonlinear W" design, but was
#   redesigned here after finding it pathological -- see Details -- and the
#   paper's own DGP2 was subsequently redesigned to match).
# Author: Brant Callaway
# Last update: 2026-08-22
# Date created: 2026-07-25
# =============================================================================

#' @title Simulate Panel Data with Bad Controls
#'
#' @description Generates a staggered difference-in-differences panel
#'   dataset matching the Monte Carlo designs in Caetano, Callaway, Payne,
#'   and Sant'Anna (2026), where a time-varying covariate X is affected by
#'   treatment (a bad control). Returns the known group-time, event-study,
#'   and overall ATT alongside the data for testing estimators against.
#'
#' @param n Number of units (default 2000)
#' @param T_max Number of time periods (default 4)
#' @param groups Integer vector of possible treatment-adoption periods,
#'   besides never-treated (default \code{2:T_max}). Values must be between
#'   2 and \code{T_max}, since every unit needs at least one pre-period.
#' @param dgp Which counterfactual evolution equation for X_t(0) to use:
#'   \code{"dgp1"} (linear W), \code{"dgp2"} (nonlinear W), \code{"dgp3"}
#'   (nonlinear in (X(t-1), Z), no W -- Simple Covariate Unconfoundedness
#'   holds), \code{"dgp4"} (linear W, coefficient 1 on the lag -- parallel
#'   trends for the bad control given (W,Z) holds exactly, see Details), or
#'   \code{"dgp5"} (nonlinear W plus an \eqn{X_{t-1} \times W} interaction --
#'   something a linear model cannot represent at all, unlike a curved but
#'   additive term; see Details)
#' @param lambda How much treatment shifts X at event time 0 (default 0.5)
#' @param delta Direct effect of treatment on Y at event time 0, net of the
#'   effect transmitted through X (default 0.5)
#' @param kappa Growth rate of the treatment effect with event time
#'   \code{e = t - g}; effects at event time e are \code{(1 + kappa * e)}
#'   times their event-time-0 value (default 0.5)
#' @param beta_drift Drift rate of the loading on X(0) in the outcome
#'   equation across calendar time (default 0.2); see Details. Set to 0 to
#'   hold the loading fixed at 1 in every period.
#' @param binary_bad_control Logical; if \code{TRUE}, the bad control X is
#'   binary instead of continuous, generated by treating the usual X(0)
#'   equations (baseline and \code{dgp}-specific evolution) as a logit index
#'   for a Bernoulli draw, and treatment as a shift in that index rather
#'   than a level shift in X. See Details.
#'
#' @return A list with:
#' \describe{
#'   \item{data}{Panel data.frame with columns id, period, G, D, Y, X, Z, W}
#'   \item{true_att_gt}{data.frame(g, t, att): the true ATT(g,t) for every
#'     valid group-time cell. Computed exactly from the DGP parameters when
#'     \code{binary_bad_control = FALSE}; when \code{TRUE}, there is no
#'     closed form (the shift in E(X) varies by unit), so this is instead
#'     the realized average over this sample's group-g cohort, same as
#'     \code{true_att_by_e}/\code{true_att_overall} below}
#'   \item{true_att_by_e}{data.frame(e, att): the true event-study ATT at
#'     each realized event time, averaged over the (g,t) cells that share
#'     that event time in this sample}
#'   \item{true_att_overall}{Realized sample average of the true individual
#'     effect across every treated (i,t) observation in this sample}
#' }
#'
#' @details
#' Common structure (shared across all \code{dgp} choices): \eqn{Z_i,\eta_i
#' \sim N(0,1)} and \eqn{W_i = 0.8\eta_i + 0.3Z_i + 0.2\varepsilon^W_i} are
#' time-invariant unit characteristics; \eqn{\eta_i} is unobserved.
#' Treatment group is assigned by splitting units into equal-sized bins of
#' the latent index \eqn{0.2Z_i + 0.4W_i + 0.3\eta_i + \varepsilon^D_i},
#' with the lowest bin never-treated and successive bins assigned to
#' \code{groups} in increasing order.
#'
#' \eqn{X_{i1} = 0.5\eta_i + 0.4Z_i + 0.3\varepsilon^{X_1}_i}, and for
#' \eqn{t \ge 2}, \eqn{X_{it}(0)} evolves according to the
#' \code{dgp}-specific equation (redrawing fresh noise every period):
#' \itemize{
#'   \item dgp1: \eqn{0.7 X_{i,t-1}(0) + 0.3Z_i + 0.2W_i + 0.15}. Matches the
#'     paper's actual Monte Carlo design, including the "Exclude BC" finding
#'     that dropping the bad control entirely stays nearly unbiased there
#'     specifically.
#'   \item dgp2: \eqn{0.7 X_{i,t-1}(0) + 0.3Z_i + 0.2W_i + 0.03 W_i^2 + 0.15}.
#'     The "nonlinear W" design, matching the paper's own DGP2 exactly. An
#'     earlier version of the paper's DGP2 used a larger quadratic
#'     coefficient (\eqn{0.15W_i^2} added to dgp1's equation), which put the
#'     quadratic term's vertex at \eqn{W = -0.667}, well inside \eqn{W}'s
#'     support (\eqn{SD(W) \approx 0.88}), making the map from \eqn{W} to
#'     \eqn{X_{it}(0)} two-to-one for nearly the whole population -- a
#'     pathological non-monotonicity, not just "nonlinearity," that
#'     specifically broke \code{dr_ml_attgt()}'s \eqn{\omega_0} (which
#'     conditions on \eqn{(X_{it}, X_{i,t-1}, Z)}, not \eqn{W}, and so must
#'     implicitly marginalize over a non-invertible \eqn{W}). This package's
#'     dgp2 keeps the same linear coefficient on \eqn{W} as dgp1 (0.2, so it
#'     still reads as "dgp1 plus one added wrinkle"), but with a small
#'     enough quadratic coefficient (0.03) that the vertex sits at
#'     \eqn{W = -3.33} (about 3.8 SDs out) -- safely beyond what any
#'     realistic sample reaches, while still contributing a real, detectable
#'     nonlinearity (about 13\% of the linear term's own size at 1 SD of
#'     \eqn{W}). The paper's own DGP2 was subsequently redesigned to use
#'     this same \eqn{0.03W_i^2} coefficient, so the two now match exactly.
#'   \item dgp3: \eqn{0.7 X_{i,t-1}(0) + 0.3Z_i + 0.4 X_{i,t-1}(0) Z_i +
#'     0.2 X_{i,t-1}(0)^2 + 0.15} (no W). Matches the paper's actual Monte
#'     Carlo design.
#'   \item dgp4: \eqn{X_{i,t-1}(0) + 0.3Z_i + 0.2W_i + 0.15}. The coefficient
#'     of 1 on the lag (a random walk with drift in \eqn{(Z,W)}), unlike
#'     dgp1's 0.7, is deliberate: it makes \eqn{\Delta X_{it}(0) = X_{it}(0)
#'     - X_{i,t-1}(0)} itself a function of \eqn{(Z,W)} alone (plus
#'     independent noise), so parallel trends for the bad control given
#'     \eqn{(W,Z)} (`app:bad-control-parallel-trends` in the supplementary
#'     appendix) holds exactly under dgp4, alongside Covariate
#'     Unconfoundedness given \eqn{(X_{t-1},W,Z)}. Does not attempt to match
#'     any Monte Carlo design in the paper, and exists only to test the
#'     parallel-trends identification strategy.
#'   \item dgp5: \eqn{0.7 X_{i,t-1}(0) + 0.3Z_i + 0.2W_i + 0.03 W_i^2 +
#'     0.05 X_{i,t-1}(0) W_i + 0.15}. dgp2's equation plus an
#'     \eqn{X_{t-1} \times W} interaction. Unlike a curved-but-additive term,
#'     an interaction is something a linear model (as in
#'     \code{imputation_attgt()}'s Step 1) cannot represent at all, no
#'     matter how strong -- a categorical, not just approximate,
#'     misspecification. Meant to show a bigger separation between
#'     Imputation and \code{dr_ml_attgt()} than dgp2 does, since forests
#'     capture interactions natively without needing to be told where to
#'     look. The interaction coefficient (0.05) was chosen empirically: it's
#'     the smallest of several tried that still gives Imputation clearly
#'     larger (roughly double or more) bias than dgp2 does, while keeping
#'     \code{dr_ml_attgt()}'s own analytical-SE calibration reasonable
#'     (larger coefficients tried, e.g. 0.10, gave a starker bias gap but
#'     degraded \code{nuisance_method = "ml"}'s SE calibration, apparently
#'     worsening rather than improving with \code{n} -- a real, persistent
#'     problem rather than finite-sample noise, unlike dgp5's own milder
#'     behavior, which does improve with \code{n}).
#' }
#' each plus \eqn{0.3\varepsilon^{X_t}_i}.
#'
#' The untreated outcome is \eqn{Y_{it}(0) = 0.3t + 0.5\eta_i + 0.3Z_i +
#' \beta_t X_{it}(0) + 0.3\varepsilon^Y_{it}}, with a time-varying loading
#' \eqn{\beta_t = 1 + \code{beta\_drift}(t-2)} (equal to 1 at t=2 regardless
#' of \code{beta_drift}). Once treated (period \eqn{t \ge G_i}, event time
#' \eqn{e = t - G_i}), the observed covariate and outcome are
#' \eqn{X_{it} = X_{it}(0) + \lambda_e} and \eqn{Y_{it} = Y_{it}(0) + \beta_t
#' \lambda_e + \delta_e}, where \eqn{\lambda_e = \lambda(1+\kappa e)} and
#' \eqn{\delta_e = \delta(1+\kappa e)}. The \eqn{\beta_t \lambda_e} term
#' routes the treatment's effect on X through the (time-varying) X-Y
#' relationship, giving true \eqn{\ATT(g,t) = \beta_t \lambda_e + \delta_e}.
#'
#' The true \eqn{\ATT(g,t)} only ever depends on \eqn{\beta_t} at the
#' post-treatment period \eqn{t}, which equals 1 whenever \eqn{t=2}
#' regardless of \code{beta_drift} -- so with the defaults, \code{T_max = 2,
#' groups = 2} already gives true \eqn{\ATT = \delta+\lambda = 1.00}. But
#' \code{beta_drift != 0} still makes \eqn{\beta_1 \ne \beta_2}, so an
#' estimator that assumes a constant X-Y loading across periods (as linear
#' Imputation implicitly does) will show bias in that case even though the
#' true ATT value matches the paper. To reproduce the paper's two-period
#' designs exactly, including the constant-loading assumption, set
#' \code{beta_drift = 0} as well.
#'
#' When \code{binary_bad_control = TRUE}, the same equations for X_i1 and
#' X_it(0) (dropping their additive noise term) are used as a logit index
#' instead of a direct value: \eqn{X_{i1} \sim \text{Bernoulli}(\Lambda(0.5
#' \eta_i + 0.4 Z_i))} and \eqn{X_{it}(0) \sim
#' \text{Bernoulli}(\Lambda(\text{evolve}_x))}, where \eqn{\Lambda} is the
#' logistic CDF. Treatment shifts the index rather than the level:
#' \eqn{X_{it}(1) \sim \text{Bernoulli}(\Lambda(\text{evolve}_x +
#' \lambda_e))}. This reuses each \code{dgp}'s existing evolution equation
#' unchanged, so \code{dgp1 + binary_bad_control = TRUE} is the case where
#' the imputation estimator's binary Step 1 (logistic regression) is
#' correctly specified, the same role \code{dgp1} plays for the continuous,
#' OLS Step 1.
#'
#' @examples
#' sim <- simulate_bad_controls(n = 500, dgp = "dgp1")
#' head(sim$data)
#' sim$true_att_gt
#' sim$true_att_overall
#'
#' # Collapses exactly to the paper's two-period design
#' sim2 <- simulate_bad_controls(n = 500, T_max = 2, groups = 2, dgp = "dgp1",
#'                                beta_drift = 0)
#' sim2$true_att_overall
#'
#' @export
simulate_bad_controls <- function(n = 2000, T_max = 4, groups = 2:T_max,
                                  dgp = c("dgp1", "dgp2", "dgp3", "dgp4", "dgp5"),
                                  lambda = 0.5, delta = 0.5, kappa = 0.5,
                                  beta_drift = 0.2,
                                  binary_bad_control = FALSE) {

  dgp <- match.arg(dgp)
  groups <- sort(unique(groups))
  if (any(groups < 2 | groups > T_max)) {
    stop("`groups` must be between 2 and T_max, so every unit has a pre-period.")
  }
  ng <- length(groups)

  # --- Time-invariant unit characteristics ------------------------------
  Z <- stats::rnorm(n)
  eta <- stats::rnorm(n)
  W <- 0.8 * eta + 0.3 * Z + 0.2 * stats::rnorm(n)

  # --- Staggered treatment-group assignment ------------------------------
  # Split into (ng + 1) equal-sized bins of the selection index: the lowest
  # bin is never-treated, successive bins get `groups` in increasing order.
  treat_latent <- 0.2 * Z + 0.4 * W + 0.3 * eta + stats::rnorm(n)
  qs <- stats::quantile(treat_latent, probs = seq(0, 1, length.out = ng + 2))
  bin <- cut(treat_latent, breaks = qs, include.lowest = TRUE, labels = FALSE)
  G <- c(0L, groups)[bin]

  # --- X_t(0): baseline plus DGP-specific evolution, fresh noise each t --
  # idx_mat holds the linear index driving X_t(0) at every period: the
  # conditional mean directly when binary_bad_control = FALSE, or the logit
  # index for a Bernoulli draw when binary_bad_control = TRUE.
  X0 <- matrix(NA_real_, nrow = n, ncol = T_max)
  idx_mat <- matrix(NA_real_, nrow = n, ncol = T_max)
  idx_mat[, 1] <- 0.5 * eta + 0.4 * Z
  X0[, 1] <- if (binary_bad_control) {
    stats::rbinom(n, 1, stats::plogis(idx_mat[, 1]))
  } else {
    idx_mat[, 1] + 0.3 * stats::rnorm(n)
  }

  evolve_x <- switch(dgp,
    dgp1 = function(x_lag) 0.7 * x_lag + 0.3 * Z + 0.2 * W + 0.15,
    dgp2 = function(x_lag) 0.7 * x_lag + 0.3 * Z + 0.2 * W + 0.03 * W^2 + 0.15,
    dgp3 = function(x_lag) 0.7 * x_lag + 0.3 * Z + 0.4 * x_lag * Z + 0.2 * x_lag^2 + 0.15,
    dgp4 = function(x_lag) x_lag + 0.3 * Z + 0.2 * W + 0.15,
    dgp5 = function(x_lag) 0.7 * x_lag + 0.3 * Z + 0.2 * W + 0.03 * W^2 + 0.05 * x_lag * W + 0.15
  )
  for (t in 2:T_max) {
    idx_mat[, t] <- evolve_x(X0[, t - 1])
    X0[, t] <- if (binary_bad_control) {
      stats::rbinom(n, 1, stats::plogis(idx_mat[, t]))
    } else {
      idx_mat[, t] + 0.3 * stats::rnorm(n)
    }
  }

  # --- Y_t(0): time-varying loading on X(0), fresh noise each t ----------
  Y0 <- matrix(NA_real_, nrow = n, ncol = T_max)
  beta_t <- 1 + beta_drift * ((1:T_max) - 2)
  theta_t <- 0.3 * (1:T_max)
  for (t in 1:T_max) {
    Y0[, t] <- theta_t[t] + 0.5 * eta + 0.3 * Z + beta_t[t] * X0[, t] +
      0.3 * stats::rnorm(n)
  }

  # --- Build panel with observed X, Y under dynamic treatment effects ----
  panel <- expand.grid(id = 1:n, period = 1:T_max)
  panel$Z <- Z[panel$id]
  panel$W <- W[panel$id]
  panel$G <- G[panel$id]
  panel$D <- as.integer(panel$G > 0 & panel$period >= panel$G)
  panel$e <- ifelse(panel$D == 1, panel$period - panel$G, NA_integer_)

  lambda_e <- lambda * (1 + kappa * panel$e)
  delta_e <- delta * (1 + kappa * panel$e)
  beta_period <- beta_t[panel$period]

  panel$X0 <- X0[cbind(panel$id, panel$period)]
  panel$Y0 <- Y0[cbind(panel$id, panel$period)]
  panel$idx <- idx_mat[cbind(panel$id, panel$period)]

  if (binary_bad_control) {
    # Treatment shifts the logit index rather than the level, so the shift
    # in E[X] is Lambda(idx+lambda_e)-Lambda(idx) -- unit-specific, unlike
    # the continuous case's constant lambda_e. lambda_e is NA for D=0 rows
    # (panel$e is NA there); substitute 0 there since it's unused anyway,
    # to avoid passing NA probabilities to rbinom().
    lambda_e_safe <- lambda * (1 + kappa * ifelse(is.na(panel$e), 0, panel$e))
    p0 <- stats::plogis(panel$idx)
    p1 <- stats::plogis(panel$idx + lambda_e_safe)
    panel$X <- ifelse(panel$D == 1, stats::rbinom(nrow(panel), 1, p1), panel$X0)
    panel$true_tau <- ifelse(panel$D == 1, beta_period * (p1 - p0) + delta_e, NA_real_)
  } else {
    panel$X <- panel$X0 + ifelse(panel$D == 1, lambda_e, 0)
    # The X-shift is routed through beta_t so that the beta_t drift genuinely
    # affects observed outcomes, not just the untreated-outcome equation.
    panel$true_tau <- ifelse(panel$D == 1, beta_period * lambda_e + delta_e, NA_real_)
  }
  panel$Y <- panel$Y0 + ifelse(panel$D == 1, panel$true_tau, 0)

  data <- panel[, c("id", "period", "G", "D", "Y", "X", "Z", "W")]
  data <- data[order(data$id, data$period), ]
  rownames(data) <- NULL

  # --- True ATT(g,t) -------------------------------------------------------
  gt_grid <- do.call(rbind, lapply(groups, function(g) {
    data.frame(g = g, t = g:T_max)
  }))
  gt_grid$e <- gt_grid$t - gt_grid$g

  if (binary_bad_control) {
    # No closed form here (unlike the continuous case below): the shift in
    # E[X] is Lambda(idx+lambda_e)-Lambda(idx), which depends on each unit's
    # own idx. Average over this sample's group-g cohort at period t instead
    # -- idx_mat already holds every unit's counterfactual index at every
    # period, treated or not.
    gt_grid$att <- vapply(seq_len(nrow(gt_grid)), function(i) {
      g <- gt_grid$g[i]
      t <- gt_grid$t[i]
      lambda_gt <- lambda * (1 + kappa * gt_grid$e[i])
      idx_gt <- idx_mat[G == g, t]
      mean(beta_t[t] * (stats::plogis(idx_gt + lambda_gt) - stats::plogis(idx_gt)) +
             delta * (1 + kappa * gt_grid$e[i]))
    }, numeric(1))
  } else {
    # Closed form, no sampling variation: the shift lambda_e is the same
    # constant for every unit at a given event time.
    gt_grid$att <- beta_t[gt_grid$t] * (lambda * (1 + kappa * gt_grid$e)) +
      delta * (1 + kappa * gt_grid$e)
  }
  true_att_gt <- gt_grid[, c("g", "t", "att")]

  # --- True event-study and overall ATT: realized averages in this sample
  treated_obs <- panel[panel$D == 1, ]
  true_att_by_e <- stats::aggregate(true_tau ~ e, data = treated_obs, FUN = mean)
  names(true_att_by_e) <- c("e", "att")
  true_att_overall <- mean(treated_obs$true_tau)

  list(
    data = data,
    true_att_gt = true_att_gt,
    true_att_by_e = true_att_by_e,
    true_att_overall = true_att_overall
  )
}
